PROCEDURE SP_EXPT_VENDA (
	PAR_FROM_DATE  IN  DATE,
	PAR_TO_DATE    IN  DATE,
	PAR_COD_LOJA   IN  NUMBER DEFAULT NULL,
	PAR_COD_FOR    IN  NUMBER DEFAULT NULL
) IS
	T_TYPE_FILE_TARGET  UTL_FILE.FILE_TYPE;
	V_NOME_FILE_TARGET  NVARCHAR2(100);
	V_DIR_FILE          NVARCHAR2(100);
	V_ERRO              CLOB;

	/* CURSOR DE BUSCA DO ARQUIVO */
	CURSOR CUR IS
	SELECT 
		'VDA_DATA' || '|' || 'VDA_LOJA' || '|' || 'VDA_PROD' || '|' || 'VDA_QTD' AS LINE_TARGET
	FROM 
		DUAL
	UNION ALL
	SELECT 
		TO_CHAR(VDA_DATA,'YYYY-MM-DD')
		|| '|"' || TO_CHAR(VDA_LOJA) || '"' || '|"' || TO_CHAR(VDA_PROD) || '"'
		|| '|' || TO_CHAR((NVL(VDA_QTD,0)),'FM99999999990.000')
	FROM (
		SELECT 
			TRUNC(VDA_DATAHORA)     AS VDA_DATA,
			--VDA_LOJA || '_' || VDA_PROD as VDA_LOJA_PROD,
			99                      AS VDA_LOJA,
			--VDA_PROD,
			97                      AS VDA_PROD, -- quando exportei tinha 97 produtos
			SUM(VDA_QTD)            AS VDA_QTD
		FROM 
			PROJETOS.V_TAB_VENDA_GERAL VD
		WHERE 
			VD.VDA_DATAHORA BETWEEN PAR_FROM_DATE AND PAR_TO_DATE + 86399 / 86400
			AND VD.VDA_KIT IN ( 0,2 )
			AND VD.VDA_PROD IN (
				SELECT 
					PROD_CODIGO
				FROM 
					PROJETOS.TAB_PRODUTO T
				WHERE 
					T.PROD_SECAO = 14
					AND T.PROD_GRUPO       = 2
					AND T.PROD_SUBGRUPO    = 2
			)
		GROUP BY TRUNC(VDA_DATAHORA),
			99,
			97
	) QRY;
BEGIN

	IF PAR_FROM_DATE IS NULL THEN
		V_ERRO := 'Data De não informada.';
		DBMS_OUTPUT.PUT_LINE(V_ERRO);
		RETURN;
	END IF;
	IF PAR_TO_DATE IS NULL THEN
		V_ERRO := 'Data Até não informada.';
		DBMS_OUTPUT.PUT_LINE(V_ERRO);
		RETURN;
	END IF; 

	-- SE A DATA INFORMADA ATÉ FOR MENOR QUE A DATA DE, ENTÃO SAIR
	IF PAR_TO_DATE < PAR_FROM_DATE THEN
		V_ERRO := 'Data ATÉ não pode ser menor que data DE.';
		DBMS_OUTPUT.PUT_LINE(V_ERRO);
		RETURN;
	END IF;
	
	BEGIN
		V_ERRO              := NULL;

		/* NOMES E DIRETÓRIO DOS ARQUIVOS */
		V_NOME_FILE_TARGET  := 'lovatti_venda_sorvetes_' || TO_CHAR(PAR_FROM_DATE,'YYYYMMDD') || '_' || TO_CHAR(PAR_TO_DATE,'YYYYMMDD') || '.csv';
		V_DIR_FILE          := '/cloudfs/dbx/backup/EXPORTACOES/Lovatti';

		/* ABRE OS ARQUIVOS PARA GRAVAÇÃO */
		T_TYPE_FILE_TARGET  := UTL_FILE.FOPEN(V_DIR_FILE,V_NOME_FILE_TARGET,'W');
  
		/* LOOP NO CURSOR PARA GRAVAÇÃO DAS LINHAS */
		FOR REG IN CUR LOOP
			/* ARQUIVO TARGET_SERIES */
			UTL_FILE.PUTF(T_TYPE_FILE_TARGET,REG.LINE_TARGET);
			UTL_FILE.NEW_LINE(T_TYPE_FILE_TARGET);
		END LOOP;

		/* FECHAR OS ARQUIVOS */
		UTL_FILE.FFLUSH(T_TYPE_FILE_TARGET);
		UTL_FILE.FCLOSE(T_TYPE_FILE_TARGET);
	EXCEPTION
		WHEN OTHERS THEN
			V_ERRO := 'Erro ao criar os arquivos csv em disco.'; -- GRAVA EVENTO DE ERRO 
			DBMS_OUTPUT.PUT_LINE(V_ERRO);
			RAISE_APPLICATION_ERROR(-20001,V_ERRO,TRUE);
			RETURN; -- FINALIZA A PROCEDURE   
	END;
END SP_EXPT_VENDA;